// Code generated by Slice Machine. DO NOT EDIT.

import Bulletpoints from './Bulletpoints/index.svelte';
import ContactForm from './ContactForm/index.svelte';
import Hero from './Hero/index.svelte';
import Image from './Image/index.svelte';
import ImageCards from './ImageCards/index.svelte';
import Quote from './Quote/index.svelte';
import Text from './Text/index.svelte';
import TextWithImage from './TextWithImage/index.svelte';
import ThreeGridLayout from './ThreeGridLayout/index.svelte';

export const components = {
	bulletpoints: Bulletpoints,
	contact_form: ContactForm,
	hero: Hero,
	image: Image,
	image_cards: ImageCards,
	quote: Quote,
	text: Text,
	text_with_image: TextWithImage,
	three_grid_layout: ThreeGridLayout
};
